<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise .then() and .catch() </title>
</head>

<body>
    <script>
        /*let p1 = new Promise((resolve, reject) => {
            console.log("promises is panding");
            setTimeout(() => {
                resolve(true)
            }, 2000);
        })
        let p2 = new Promise((resolve, reject) => {
            console.log("promises is panding");
            setTimeout(() => {
                reject(new Error("some error occer"))
            }, 2000);
        })

        p1.then((value) => {
            console.log(value);
        })
        p2.catch((error) => {
            console.log("Some error occer");
        });*/
        


        // Creating a Promise that resolves after 2 seconds
const myPromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("Promise resolved!"); // Fulfill the Promise with the value "Promise resolved!"
  }, 2000);
});

// Using then() on the resolved value
myPromise.then((result) => {
  console.log(result); // Output: "Promise resolved!"
}).catch((error) => {
  console.error("Error:", error); // Not executed in this example as there is no rejection
});

const myPromises = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error("Promise rejected!")); // Reject the Promise with an error
  }, 2000);
});

// Using catch() to handle a rejected Promise
myPromise.then((result) => {
  console.log(result); // Not executed in this example due to rejection
}).catch((error) => {
  console.error("Error:", error); // Output: "Error: Error: Promise rejected!"
});

    </script>
</body>

</html>